# Generated by Django 5.0.7 on 2024-12-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gearBox", models.CharField(max_length=50)),
                ("fuelType", models.CharField(max_length=50)),
                ("consumption", models.DecimalField(decimal_places=1, max_digits=4)),
                ("engineVolume", models.DecimalField(decimal_places=1, max_digits=3)),
                ("enginePower", models.IntegerField(blank=True, null=True)),
                ("prices", models.CharField(default="fuck", max_length=1024)),
                (
                    "mainImage",
                    models.ImageField(blank=True, null=True, upload_to="cars/"),
                ),
                ("additionalFunctions", models.JSONField(default=list)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                    ),
                ),
            ],
        ),
    ]
