# Generated by Django 5.0.7 on 2024-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="prices",
            field=models.JSONField(),
        ),
    ]
