# Generated by Django 5.1.3 on 2024-12-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='additionalFunctions',
            new_name='additional_functions',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='enginePower',
            new_name='engine_power',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='engineVolume',
            new_name='engine_volume',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuelType',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='gearBox',
            new_name='gear_box',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='mainImage',
            new_name='main_image',
        ),
    ]
