# Generated by Django 5.1.4 on 2025-01-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('buiness', 'Бізнес'), ('economy', 'Економ'), ('middle', 'Середній')], default='miidle', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
