# Generated by Django 5.1.4 on 2025-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_car_class_alter_car_brand_alter_car_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='additional_functions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('buiness', 'Бізнес'), ('economy', 'Економ'), ('middle', 'Середній')], default='middle', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний'), ('hybrid', 'Гібрид')], default='petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box',
            field=models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автоматична'), ('semi-automatic', 'Напівавтоматична')], default='manual', max_length=50),
        ),
    ]
