# Generated by Django 5.1.4 on 2025-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_location_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
