# Generated by Django 5.1.4 on 2025-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('buisness', 'Бізнес'), ('economy', 'Економ'), ('middle', 'Середній')], default='middle', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
