# Generated by Django 5.1.4 on 2025-01-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_car_class_alter_car_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний')], default='petrol', max_length=50),
        ),
    ]
