# Generated by Django 5.1.4 on 2025-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine_volume',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний'), ('hybrid', 'Гібрид')], default='petrol', max_length=50),
        ),
    ]
