# Generated by Django 5.1.4 on 2025-01-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_engine_volume_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний')], default='petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.location'),
        ),
    ]
