# Generated by Django 5.1.4 on 2025-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_rental_additional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='comment',
            field=models.TextField(blank=True, help_text='Додаткові коментарі або побажання від користувача', null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
