# Generated by Django 5.1.4 on 2025-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_rental_comment_alter_rental_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картка'), ('cash', 'Готівка')], default='card', max_length=20),
        ),
    ]
