# Generated by Django 5.1.4 on 2025-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_rental_is_paid_rental_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картка'), ('cash', 'Готівка')], default='cash', max_length=20),
        ),
    ]
