# Generated by Django 5.1.4 on 2025-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0007_location_rental_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
