# Generated by Django 5.1.4 on 2025-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0008_rental_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='rental',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Прийнято'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
    ]
