# Generated by Django 5.1.4 on 2025-01-16 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0009_remove_rental_is_approved_rental_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='phone_number',
            field=models.CharField(blank=True, default='+380', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефону має бути у форматі +380123456789', regex='^\\+380\\d{9}$')]),
        ),
    ]
