# Generated by Django 5.1.4 on 2025-01-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0010_rental_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
