# Generated by Django 5.1.4 on 2025-01-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0011_remove_rental_location_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='phone_number',
            field=models.CharField(default='+380', max_length=15),
        ),
    ]
