# Generated by Django 5.1.3 on 2024-12-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gearBox", models.CharField(blank=True, max_length=50, null=True)),
                ("fuelType", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "consumption",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "engineVolume",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("enginePower", models.IntegerField(blank=True, null=True)),
                ("prices", models.JSONField(blank=True, null=True)),
                (
                    "mainImage",
                    models.ImageField(blank=True, null=True, upload_to="cars/"),
                ),
                (
                    "additionalFunctions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.car",
                    ),
                ),
            ],
        ),
    ]
